#!/bin/bash

# Export AWS credentials
export AWS_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
export AWS_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}

# Get input arguments
input_folder=$1
cache_key=$2
file_name=$3

md5_cache_key=$(echo -n $cache_key | md5sum | awk '{print $1}')
tar_file="${md5_cache_key}.tgz"

if [ "$file_name" != "" ]; then
 tar_file="${file_name}.tgz"
fi

echo "Input folder: $input_folder"
echo "Cache key: $cache_key"
echo "tar file: $tar_file"


S3_FOLDER="$S3_BUCKET/cache_folders/$cache_key/$tar_file"
# Upload to a temporary key first so a failed tar never becomes the cache
S3_TMP_FOLDER="$S3_BUCKET/cache_folders/$cache_key/.$tar_file.uploading-$$-$(date +%s)"

echo "s3 file: $S3_FOLDER"

if head_error=$(aws s3api head-object --bucket "$S3_BUCKET" --key "cache_folders/$cache_key/$tar_file" 2>&1 >/dev/null); then
  echo "File exists!"
else
  head_status=$?
  case "$head_error" in
    *"An error occurred (404) when calling the HeadObject operation:"*)
      echo "File not found: s3://$S3_FOLDER. Will create new one."
      ;;
    *)
      printf '%s\n' "$head_error" >&2
      echo "Failed to check cache: s3://$S3_FOLDER (exit $head_status)" >&2
      exit "$head_status"
      ;;
  esac
  start_at=$(date)
  echo "stream to s3"
  # Stream the archive straight to S3 instead of writing it to disk and reading it back
  tar -zcf - -C "$input_folder" . | aws s3 cp - "s3://$S3_TMP_FOLDER"
  pipe_status=("${PIPESTATUS[@]}")
  if [ "${pipe_status[1]}" -ne 0 ]; then
    exit "${pipe_status[1]}"
  fi
  if [ "${pipe_status[0]}" -ne 0 ]; then
    aws s3 rm "s3://$S3_TMP_FOLDER"
    exit "${pipe_status[0]}"
  fi
  aws s3 mv "s3://$S3_TMP_FOLDER" "s3://$S3_FOLDER" || exit $?
  echo "done $start_at => $(date)"
fi
