#!/bin/bash

# Export AWS credentials
export AWS_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
export AWS_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}

# Get input arguments
input_folder=$1
cache_key=$2
file_name=$3

md5_cache_key=$(echo -n $cache_key | md5sum | awk '{print $1}')
tar_file="${md5_cache_key}.tgz"

if [ "$file_name" != "" ]; then
 tar_file="${file_name}.tgz"
fi

echo "Input folder: $input_folder"
echo "Cache key: $cache_key"
echo "tar file: $tar_file"


S3_FOLDER="$S3_BUCKET/cache_folders/$cache_key/$tar_file"
LOCAL_FILE="/tmp/save-cache/$tar_file"
mkdir -p /tmp/save-cache
echo "S3_TMP_DIR: $S3_TMP_DIR"
if [ "$S3_TMP_DIR" != "" ]; then
  mkdir -p $S3_TMP_DIR/save-cache
  LOCAL_FILE="$S3_TMP_DIR/save-cache/$tar_file"
fi

echo "s3 file: $S3_FOLDER"
echo "local file: $LOCAL_FILE"

rm -f "$LOCAL_FILE"
# cd $input_folder && zip -r $LOCAL_FILE * && cd -

if head_error=$(aws s3api head-object --bucket "$S3_BUCKET" --key "cache_folders/$cache_key/$tar_file" 2>&1 >/dev/null); then
  echo "File exists!"
else
  head_status=$?
  case "$head_error" in
    *"An error occurred (404) when calling the HeadObject operation:"*)
      echo "File not found: s3://$S3_FOLDER. Will create new one."
      ;;
    *)
      printf '%s\n' "$head_error" >&2
      echo "Failed to check cache: s3://$S3_FOLDER (exit $head_status)" >&2
      exit "$head_status"
      ;;
  esac
  start_at=$(date)
  tar -zcf "$LOCAL_FILE" -C "$input_folder" . || exit $?
  echo "done $start_at => $(date)"
  echo "put to s3"
  aws s3 cp "$LOCAL_FILE" "s3://$S3_FOLDER"
fi
